// AssetPipelineSwiftKit — umbrella module.
//
// All public types in this Swift package are exposed to Crystal through
// Objective-C using the `@objc(APSK*)` naming convention. The `APSK` prefix
// avoids any chance of collision with Foundation, UIKit, or AppKit classes.
//
// Tokens: `AssetPipelineTokens.swift` is GENERATED by Phase 1's
// `UI::DesignTokens::AppleGenerator` and lives at
// `src/ui/design_tokens/dist/AssetPipelineTokens.swift`. It is consumed by
// this package via a symlink at
// `swift/AssetPipelineSwiftKit/Sources/AssetPipelineTokens/AssetPipelineTokens.swift`.
// Brand overrides in Crystal regenerate the dist file; the next Swift build
// picks them up automatically.
//
// Runtime initialization order (validated by Phase 3 §10.4):
//
//   1. Swift host app launches (`@main` on iOS, `NSApplicationMain` on macOS).
//   2. Host calls `crystal_init` / `crystal_main` (existing entry).
//   3. Crystal's `Bridge.initialize_runtime` runs `GC.init` and then
//      `install_swiftkit_action_trampoline` which calls
//      `APSKRuntime.initializeWithActionTrampoline:` (this module).
//   4. Subsequent `crystal_render_slug` calls are free to invoke any
//      `APSK*Facade.make*` method.
import Foundation

/// The umbrella class exists primarily so the linker keeps the module
/// active even when only `@objc` static methods are reachable. Crystal
/// touches this class once during runtime init via `objc_getClass`.
@objc(APSKAssetPipelineSwiftKit)
public final class AssetPipelineSwiftKitModule: NSObject {
    /// Touch point used by spec helpers and the runtime trampoline to confirm
    /// the static library has actually been linked in.
    @objc public static let isLoaded: Bool = true
}
