# Emits a deterministic Swift source file (AssetPipelineTokens.swift) from a
# UI::DesignTokens::Tokens instance, consumed by the Apple SwiftUI bridge.

require "../../design_tokens"

module UI
  module DesignTokens
    # Emits a Swift file from a `UI::DesignTokens::Tokens` instance.
    #
    # Output is consumed by Phase 3 (SwiftUI bridge). Deterministic: same input
    # bytes → same output bytes.
    #
    # Mapping rules (per implementation.md §4.2):
    # - Spacing / radius rem are multiplied by 16 to convert to Apple points.
    # - Type sizes track the brand's value verbatim; the brief's "HIG default
    #   17pt body" override applies only when the brand has explicitly *not*
    #   set a size. We hold the brand's value through faithfully — the
    #   default Tokens already encodes the body at 1.0rem (16pt) which is
    #   the standard cross-platform body, and a downstream SwiftUI consumer
    #   can substitute SF Dynamic Type if they want HIG-canonical 17pt.
    # - Font.Weight mapping is documented inline.
    # - `ease_standard` → `UnitCurve.easeInOut`, `ease_emphasized` round-trips
    #   the bezier 4-tuple. `spring` is dropped — SwiftUI manages its own
    #   spring curves via `.spring()`.
    module AppleGenerator
      extend self

      HEADER = "// GENERATED by UI::DesignTokens::AppleGenerator. Do not edit by hand.\n"

      def generate(tokens : Tokens) : String
        String.build do |io|
          io << HEADER
          io << "import SwiftUI\n\n"
          io << "public enum AssetPipelineTokens {\n\n"
          emit_color_enum(io, tokens)
          io << "\n"
          emit_spacing_enum(io, tokens.spacing)
          io << "\n"
          emit_radius_enum(io, tokens.radius)
          io << "\n"
          emit_typography_enum(io, tokens.type)
          io << "\n"
          emit_motion_enum(io, tokens.motion)
          io << "\n"
          io << "    public static let touchTargetMinimumPoints: CGFloat = #{format_cgfloat(tokens.touch_target_minimum_px)}\n"
          io << "}\n"
        end
      end

      private def emit_color_enum(io : IO, tokens : Tokens) : Nil
        io << "    public enum Color {\n"
        tokens.colors_light.to_h.each do |name, color|
          io << "        public static let #{swift_field_name(name)} = SwiftUI.#{color.to_swift_color}\n"
        end
        io << "\n"
        io << "        public enum Dark {\n"
        tokens.colors_dark.to_h.each do |name, color|
          io << "            public static let #{swift_field_name(name)} = SwiftUI.#{color.to_swift_color}\n"
        end
        io << "        }\n"
        io << "    }\n"
      end

      private def emit_spacing_enum(io : IO, scale : SpacingScale) : Nil
        io << "    public enum Spacing {\n"
        scale.to_h.each do |key, value|
          field = "x#{key.gsub('.', '_')}"
          field = "px" if key == "px"
          points = key == "px" ? 1.0 : rem_to_points(value)
          io << "        public static let #{field}: CGFloat = #{format_cgfloat(points)}\n"
        end
        io << "    }\n"
      end

      private def emit_radius_enum(io : IO, scale : RadiusScale) : Nil
        io << "    public enum Radius {\n"
        io << "        public static let none: CGFloat = #{format_cgfloat(rem_to_points(scale.none))}\n"
        io << "        public static let xs: CGFloat = #{format_cgfloat(rem_to_points(scale.xs))}\n"
        io << "        public static let sm: CGFloat = #{format_cgfloat(rem_to_points(scale.sm))}\n"
        io << "        public static let md: CGFloat = #{format_cgfloat(rem_to_points(scale.md))}\n"
        io << "        public static let lg: CGFloat = #{format_cgfloat(rem_to_points(scale.lg))}\n"
        io << "        public static let xl: CGFloat = #{format_cgfloat(rem_to_points(scale.xl))}\n"
        io << "        public static let x2l: CGFloat = #{format_cgfloat(rem_to_points(scale.x2l))}\n"
        io << "        public static let card: CGFloat = #{format_cgfloat(rem_to_points(scale.card))}\n"
        io << "        public static let sheet: CGFloat = #{format_cgfloat(rem_to_points(scale.sheet))}\n"
        io << "        public static let avatar: CGFloat = #{format_cgfloat(rem_to_points(scale.avatar))}\n"
        io << "        public static let avatarLg: CGFloat = #{format_cgfloat(rem_to_points(scale.avatar_lg))}\n"
        # Pill is a sentinel — emit a literal large value rather than 9999.9375pt.
        io << "        public static let pill: CGFloat = 9999\n"
        io << "    }\n"
      end

      private def emit_typography_enum(io : IO, scale : TypeScale) : Nil
        io << "    public enum Typography {\n"
        # Apple resolves these family identifiers via SwiftUI's Font.custom.
        io << "        public static let familySans: String = #{quote(scale.family_sans)}\n"
        io << "        public static let familyDisplay: String = #{quote(scale.family_display)}\n"
        io << "        public static let familyMono: String = #{quote(scale.family_mono)}\n\n"
        io << "        public struct Step {\n"
        io << "            public let size: CGFloat\n"
        io << "            public let lineHeight: CGFloat\n"
        io << "            public let weight: Font.Weight\n"
        io << "            public let tracking: CGFloat\n"
        io << "        }\n\n"
        emit_type_step(io, "caption", scale.caption)
        emit_type_step(io, "body", scale.body)
        emit_type_step(io, "bodyEmph", scale.body_emph)
        emit_type_step(io, "title", scale.title)
        emit_type_step(io, "headline", scale.headline)
        emit_type_step(io, "display", scale.display)
        io << "    }\n"
      end

      private def emit_type_step(io : IO, name : String, step : TypeStep) : Nil
        size_pt = rem_to_points(step.size)
        # lineHeight stored as a multiplier; Swift consumers multiply by size_pt
        # to get a pt value. We emit the same multiplier verbatim.
        io << "        public static let #{name} = Step(size: #{format_cgfloat(size_pt)}, "
        io << "lineHeight: #{format_cgfloat(step.line_height * size_pt)}, "
        io << "weight: #{weight_to_swift(step.weight)}, "
        io << "tracking: #{format_cgfloat(step.tracking * size_pt)})\n"
      end

      private def emit_motion_enum(io : IO, scale : MotionScale) : Nil
        io << "    public enum Motion {\n"
        io << "        public static let durationInstant: Double = #{format_seconds(scale.duration_instant_ms)}\n"
        io << "        public static let durationFast: Double = #{format_seconds(scale.duration_fast_ms)}\n"
        io << "        public static let durationBase: Double = #{format_seconds(scale.duration_base_ms)}\n"
        io << "        public static let durationSlow: Double = #{format_seconds(scale.duration_slow_ms)}\n"
        # `ease_standard` → SwiftUI's stock easeInOut curve. Brand can switch
        # this by overriding `MotionScale.ease_standard` and regenerating; the
        # generator round-trips the CSS literal as a Swift comment so it stays
        # discoverable.
        io << "        // ease_standard CSS: #{scale.ease_standard}\n"
        io << "        public static let easeStandard = UnitCurve.easeInOut\n"
        # `ease_emphasized` parses the cubic-bezier(a, b, c, d) form and round-
        # trips the bezier 4-tuple as a Swift UnitCurve.
        emphasized_bezier = parse_cubic_bezier(scale.ease_emphasized)
        if emphasized_bezier
          x1, y1, x2, y2 = emphasized_bezier
          io << "        public static let easeEmphasized = UnitCurve.bezier(controlPoint1: CGPoint(x: #{format_cgfloat(x1)}, y: #{format_cgfloat(y1)}), controlPoint2: CGPoint(x: #{format_cgfloat(x2)}, y: #{format_cgfloat(y2)}))\n"
        else
          io << "        public static let easeEmphasized = UnitCurve.easeInOut // fallback — non-bezier source\n"
        end
        # `spring` is dropped — SwiftUI controls its own spring via `.spring()`.
        io << "    }\n"
      end

      private def rem_to_points(rem : Float64) : Float64
        # 1 rem = 16 logical points. Round to half-points (Apple convention).
        pt = rem * 16.0
        (pt * 2.0).round / 2.0
      end

      private def format_cgfloat(value : Float64) : String
        if value == value.to_i.to_f
          value.to_i.to_s
        else
          s = "%.4f" % value
          s.rstrip('0').rstrip('.')
        end
      end

      private def format_seconds(ms : Int32) : String
        seconds = ms / 1000.0
        "%.3f" % seconds
      end

      private def quote(s : String) : String
        # Swift string literal: backslash-escape backslashes and double-quotes.
        escaped = s.gsub('\\', "\\\\").gsub('"', "\\\"")
        "\"#{escaped}\""
      end

      private def swift_field_name(kebab_name : String) : String
        # "brand-primary-hover" → "brandPrimaryHover".
        parts = kebab_name.split('-')
        first = parts.first
        rest = parts[1..].map(&.capitalize)
        first + rest.join
      end

      private def weight_to_swift(w : Int32) : String
        # Map an integer CSS-style weight to the nearest SwiftUI Font.Weight.
        # Round-down by convention: 450 → .regular, 720 → .bold.
        case w
        when ..149       then ".ultraLight"
        when 150..249    then ".thin"
        when 250..349    then ".light"
        when 350..474    then ".regular"
        when 475..549    then ".medium"
        when 550..649    then ".semibold"
        when 650..749    then ".bold"
        when 750..849    then ".heavy"
        else                  ".black"
        end
      end

      # Parse "cubic-bezier(x1, y1, x2, y2)" → {x1, y1, x2, y2}. Returns nil
      # for non-bezier inputs.
      private def parse_cubic_bezier(css : String) : Tuple(Float64, Float64, Float64, Float64)?
        m = css.strip.match(/\Acubic-bezier\(\s*(-?\d*\.?\d+)\s*,\s*(-?\d*\.?\d+)\s*,\s*(-?\d*\.?\d+)\s*,\s*(-?\d*\.?\d+)\s*\)\z/i)
        return nil unless m
        {m[1].to_f, m[2].to_f, m[3].to_f, m[4].to_f}
      end
    end
  end
end
