require "spec"
require "../../../../../src/ui/design_tokens"
require "../../../../../src/ui/design_tokens/generators/apple_generator"

describe UI::DesignTokens::AppleGenerator do
  describe ".generate" do
    it "is byte-stable across two consecutive calls" do
      tokens = UI::DesignTokens::Tokens.default
      a = UI::DesignTokens::AppleGenerator.generate(tokens)
      b = UI::DesignTokens::AppleGenerator.generate(tokens)
      a.should eq(b)
    end

    it "emits the canonical generator header" do
      output = UI::DesignTokens::AppleGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should start_with("// GENERATED by UI::DesignTokens::AppleGenerator. Do not edit by hand.\n")
    end

    it "imports SwiftUI" do
      output = UI::DesignTokens::AppleGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should contain("import SwiftUI")
    end

    it "exposes Color, Spacing, Radius, Typography, Motion enums" do
      output = UI::DesignTokens::AppleGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should contain("public enum Color {")
      output.should contain("public enum Dark {")
      output.should contain("public enum Spacing {")
      output.should contain("public enum Radius {")
      output.should contain("public enum Typography {")
      output.should contain("public enum Motion {")
    end

    it "lowers spacing from rem to points (1rem == 16pt)" do
      output = UI::DesignTokens::AppleGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should contain("public static let x4: CGFloat = 16")
      output.should contain("public static let x8: CGFloat = 32")
    end

    it "exposes touchTargetMinimumPoints" do
      output = UI::DesignTokens::AppleGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should contain("public static let touchTargetMinimumPoints: CGFloat = 44")
    end

    it "emits every brand color in camelCase" do
      output = UI::DesignTokens::AppleGenerator.generate(UI::DesignTokens::Tokens.default)
      [
        "brandPrimary",
        "brandPrimaryHover",
        "surfaceCanvas",
        "textPrimary",
        "borderDefault",
        "danger",
      ].each do |name|
        output.should contain("let #{name} = SwiftUI.Color")
      end
    end

    it "matches the committed dist file" do
      output = UI::DesignTokens::AppleGenerator.generate(UI::DesignTokens::Tokens.default)
      dist_path = File.expand_path("../../../../../../src/ui/design_tokens/dist/AssetPipelineTokens.swift", __FILE__)
      committed = File.read(dist_path)
      output.should eq(committed)
    end
  end
end
