require "spec"
require "../../../../../src/ui/design_tokens"
require "../../../../../src/ui/design_tokens/generators/web_generator"

describe UI::DesignTokens::WebGenerator do
  describe ".generate" do
    it "is byte-stable across two consecutive calls" do
      tokens = UI::DesignTokens::Tokens.default
      a = UI::DesignTokens::WebGenerator.generate(tokens)
      b = UI::DesignTokens::WebGenerator.generate(tokens)
      a.should eq(b)
    end

    it "emits the canonical generator header" do
      output = UI::DesignTokens::WebGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should start_with("/* GENERATED by UI::DesignTokens::WebGenerator. Do not edit by hand. */\n")
    end

    it "contains every canonical color variable" do
      output = UI::DesignTokens::WebGenerator.generate(UI::DesignTokens::Tokens.default)

      # Both the canonical and `-rgb` paired variants must be present for
      # opinionated library colours.
      [
        "--ap-color-surface-canvas",
        "--ap-color-text-primary",
        "--ap-color-border-default",
        "--ap-color-danger",
        "--ap-color-info",
      ].each do |name|
        output.should contain(name + ":")
        output.should contain(name + "-rgb:")
      end

      # Phase 6.12A library-identity pivot: the brand_primary family resolves
      # to `Color::SYSTEM_ACCENT`. The canonical `--ap-color-brand-primary*`
      # custom property is still emitted (as `AccentColor`) but the paired
      # `-rgb` variant is intentionally omitted because the sentinel has
      # no honest RGB triple. See web_generator.cr `emit_color_vars`.
      [
        "--ap-color-brand-primary",
        "--ap-color-brand-primary-hover",
        "--ap-color-brand-primary-active",
      ].each do |name|
        output.should contain(name + ": AccentColor;")
        output.includes?(name + "-rgb:").should be_false
      end
    end

    it "emits both light and dark blocks" do
      output = UI::DesignTokens::WebGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should contain(":root {")
      output.should contain("@media (prefers-color-scheme: dark)")
      output.should contain("[data-ap-theme=\"light\"]")
      output.should contain("[data-ap-theme=\"dark\"]")
    end

    it "emits zero --amber-* aliases" do
      # The phase-1 prefix change is total: `--amber-*` is dropped wholesale.
      output = UI::DesignTokens::WebGenerator.generate(UI::DesignTokens::Tokens.default)
      output.includes?("--amber-").should be_false
    end

    it "exposes touch-target-min variable" do
      output = UI::DesignTokens::WebGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should contain("--ap-touch-target-min: 44px")
    end

    it "cascades brand overrides into the emitted CSS" do
      output = UI::DesignTokens::WebGenerator.generate(
        UI::DesignTokens::Tokens.default.with_brand(SentinelBrandForWebSpec.new)
      )
      output.should contain("--ap-color-brand-primary-rgb: 255 0 255")
    end

    it "emits spacing values matching css_config defaults" do
      output = UI::DesignTokens::WebGenerator.generate(UI::DesignTokens::Tokens.default)
      output.should contain("--ap-space-4: 1rem")
      output.should contain("--ap-space-px: 1px")
      output.should contain("--ap-space-0: 0rem")
    end

    it "matches the committed dist file" do
      output = UI::DesignTokens::WebGenerator.generate(UI::DesignTokens::Tokens.default)
      dist_path = File.expand_path("../../../../../../src/ui/design_tokens/dist/web_tokens.css", __FILE__)
      committed = File.read(dist_path)
      output.should eq(committed)
    end
  end
end

class SentinelBrandForWebSpec < UI::DesignTokens::Brand
  protected def override_color_light(palette : UI::DesignTokens::ColorPalette) : UI::DesignTokens::ColorPalette
    palette.copy_with(brand_primary: UI::DesignTokens::Color.hex("#ff00ff"))
  end
end
